name: New Feature - Request a new feature
description: Suggest an idea for the app.
labels: ["type: feature request", "status: waiting triage"]
body:
  - type: textarea
    attributes:
      label: Describe use case that the app currently doesn't cover
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
